### ISSUE TITLE
Support Apple Calendars EXDATE problem

### ISSUE THREAD

**Issue by Knogobert** [controlz/CalFileParser#4]
Apples Calendar app (formerly known as iCal) works very well except for one problem with the parser. It seems to skip the "extra" EXDATEs that come with the calendar. Apple composes them like this when there are several EXDATEs:

``` js
EXDATE;TZID=Europe/Stockholm:20160401T140000
EXDATE;TZID=Europe/Stockholm:20160408T140000
EXDATE;TZID=Europe/Stockholm:20160325T140000
```

Instead of the standard iCal way:

``` js
EXDATE:20160401T140000,20160408T140000,20160325T140000
```

(Dont worry about the TZID part, i regex that away)
I am not very experienced with PHP yet so that is why I need help with this small problem.
Hope you (or somebody) still are active and caring enough to help me with this. Thanks!

**Comment by controlz** [comment]
Hi @NipSauce 
Thanks for making an issue.

I haven't had a lot of time to maintain this project, but if I can steal a couple hours over the next week I'll look into solving this for you!
